---
title:               "Lake 2016 snRNAseq Report"
author:
  - name:            "Emir Turkes"
  - name:            "Columbia University"
date:                '`r strftime(Sys.time(), format = "%B %d, %Y")`'
bibliography:        "../lake-2016-snRNAseq.bib"
biblio-style:        apalike
link-citations:      true
output:
  html_document:
    number_sections: true
    theme:           lumen
    toc:             true
    toc_depth:       2
    toc_float:
      collapsed:     false
      smooth_scroll: false

knit:
  (function(inputFile, encoding) {rmarkdown::render(
    inputFile,
    encoding = encoding,
    output_file = "../results/lake-2016-snRNAseq-report.html"
  )})
---

```{r, include = FALSE}
#    This file is part of lake-2016-snRNAseq.
#    Copyright (C) 2019  Emir Turkes
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#    Emir Turkes can be contacted at emir.turkes@eturkes.com

knitr::opts_chunk$set(echo = TRUE)
```

<style type="text/css">

body{ /* Normal  */
  font-size: 16px;
}
h1.title {
  font-size: 35px;
}
h1 { /* Header 1 */
  font-size: 24px;
}
h2 { /* Header 2 */
  font-size: 22px;
}
h3 { /* Header 3 */
  font-size: 20px;
}
.toc-content {
  padding-left: 0px;
  padding-right: 0px;
}
div.tocify {
  width: 100%;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
  padding-left: 25px;
  text-indent: 0;
}
.tocify-subheader .tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 35px;
  text-indent: 0;
}
div.main-container {
  max-width: none;
  width: 100%;
}

</style>

*This is a broad initial analysis that prepares and characterizes the data for use in other projects.*

The background for this data is as follows:

- dbGaP Accession: [phs000833](https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs000833.v7.p1).
- Part of [SCAP-T](https://www.scap-t.org/).
- Single patient, age = 51, sex = female, NeuN + nuclei from normal mostmortem.
- 6 cortical regions: BA8, BA10, BA21, BA22, BA41, and BA17.
- Annotated into 8 excitatory and inhibitory neuronal subtypes.

This analysis was performed in R except where noted.
The source code and instructions for rerunning the analysis can be found at [github.com/eturkes/lake-2016-snRNAseq](https://github.com/eturkes/lake-2016-snRNAseq).

# Final Results

**Read just this section for the final results of the analysis and a summary of the methods.**

# ~~~~ Breakdown of Methods ~~~~ {-}

The following sections breakdown the methods used to transform the contents in `Original Data` to those in `Final Results`.

# Original Data
